### ISSUE TITLE
Use of '=' as key-value separator is causing truncation of SAS Token when used for linkedTemplatesUrlQueryString

### ISSUE THREAD

**Issue by chni1201** [mirsaeedi/dotnet-apim#1]
https://github.com/mirsaeedi/dotnet-apim/blob/7b5e75286489185d08229892277ed0bda19ef122/src/apimtemplate/Core/Extensions.cs#L42
I'm trying to use linkedTemplatesUrlQueryString: in the template generator so that I can pull the SAS token that I want to configure and read from the replace-variable.yml file but since the sas token already contains '=' (as the Azure SAS token looks like this ?sv=2019-02-02&......) the sas token value is truncated and in the parameters.json file that is generated will only have the values as follow:
"LinkedTemplatesUrlQueryString": {
      "value": "?sv"
    }

**Comment by mirsaeedi** [comment]
In the new version, `linkedTemplatesUrlQueryString` is removed. The tool generates only one template which contains all the required resources. You can just deploy the generated file using the [Azure CLI](https://github.com/mirsaeedi/dotnet-apim#deploying-arm-templates-into-apim).

By the way, the issue with having `=` in the variables is fixed now. Thanks for reporting the issue.
