### ISSUE TITLE
Enhancement: The discovery of IMappers should be automatic

### ISSUE THREAD

**Issue by mirsaeedi** [mirsaeedi/dotnet-apim#18]
Making the discovery automatic would would eliminate some of the manual work that is required to be done when adding support for new entities.

**Comment by andrewdmoreno** [comment]
@mirsaeedi - I see you are using AutoMapper for the mappers. I could probably tackle this if you needed someone to work on it.

**Comment by mirsaeedi** [comment]
Thanks @andrewdmoreno. It's gonna be tackled by #19

**Comment by mirsaeedi** [comment]
resolves by #19
