### ISSUE TITLE
How can we make "linked" parameter false, what if we don`t want to create master Template ?

### ISSUE THREAD

**Issue by saikiran-karumuri-by** [mirsaeedi/dotnet-apim#2]

**Comment by saikiran-karumuri-by** [comment]
We want to create all individual Templates and upload what ever needed. How can i achieve this?

**Comment by mirsaeedi** [comment]
In the new version, only one arm template is created which bundles all required resources. Then, you can use [Azure CLI](https://github.com/mirsaeedi/dotnet-apim#deploying-arm-templates-into-apim) to upload the generated template.
