### ISSUE TITLE
Swagger download not needed

### ISSUE THREAD

**Issue by levimatheri** [mirsaeedi/dotnet-apim#34]
Previously, swagger import would overwrite the api display name with the title. However, this is no longer the case as per [this comment](https://github.com/Azure/azure-api-management-devops-resource-kit/issues/538#issuecomment-916172315). I've verified this as well. Modify dotnet-apim tool to not download the swagger. This also prevents hitting character limits if the swagger content is large.
@mirsaeedi

**Comment by mirsaeedi** [comment]
Cool. Thanks @levimatheri. This will be address in the following week.

**Comment by levimatheri** [comment]
@mirsaeedi  Any update on this? I can send in a PR if you'd like.
