### ISSUE TITLE
Creating revision not appending `;rev=n` suffix to API name

### ISSUE THREAD

**Issue by levimatheri** [mirsaeedi/dotnet-apim#41]
In order to create a revision, one must append `;rev=n` to the API id otherwise the revision is not created. See [docs](https://docs.microsoft.com/en-us/rest/api/apimanagement/current-ga/apis/create-or-update#uri-parameters) and [code in azure-apim-devops-kit
](https://github.com/Azure/azure-api-management-devops-resource-kit/blob/d6d4f024bd8124268f6ebdc8abb0099c7d0b2a30/src/ArmTemplates/Creator/TemplateCreators/APITemplateCreator.cs#L61-L68).

![image](https://user-images.githubusercontent.com/16405269/177242464-a9c15e74-d36c-4b8b-8671-a4a01fd6b08e.png)

My yml file:
![image](https://user-images.githubusercontent.com/16405269/177240546-de96fb20-613d-4228-a056-52325362019f.png)

The `;rev=2` is not appended to the API name:
![image](https://user-images.githubusercontent.com/16405269/177240995-a8198e1b-e8d8-4ce2-a0f1-baf0f4a003a1.png)

**What I'd expect**
![image](https://user-images.githubusercontent.com/16405269/177241047-db6bcadc-7fe6-4470-89c4-708b5f17b3c4.png)

I tried to append the revision to the API name in `variableString`, but since it contains a semi-colon, it didn't work.

We need to check if `apiRevision` is specified and `isCurrent` is false, if so, append the suffix to the API id. This is the behavior [in azure-apim-devops-kit](https://github.com/Azure/azure-api-management-devops-resource-kit/blob/d6d4f024bd8124268f6ebdc8abb0099c7d0b2a30/src/ArmTemplates/Creator/TemplateCreators/APITemplateCreator.cs#L61-L68).

See also [answer from Microsoft support](https://docs.microsoft.com/en-us/answers/questions/64615/how-do-i-deploy-an-api-management-api-update-with.html): 

![image](https://user-images.githubusercontent.com/16405269/177243958-0e16b168-fcce-4601-8db7-eab059a2bf5c.png)

**Comment by levimatheri** [comment]
@mirsaeedi Let me know what you think, I'd be happy to submit a PR for this.

**Comment by mirsaeedi** [comment]
Thanks for submitting the issue. I'll have a PR ready soon.
