### ISSUE TITLE
Allow ServiceFabric backend clientCertificateId reference

### ISSUE THREAD

**Issue by levimatheri** [mirsaeedi/dotnet-apim#43]
@mirsaeedi One more haha...
We have a need to reference the Service Fabric client certificate using `clientCertificateId`. This property is available in [API version 2021-08-01](https://docs.microsoft.com/en-us/azure/templates/microsoft.apimanagement/2021-08-01/service/backends?tabs=json).

The value in the generated ARM template would be a `resourceId`, i.e. 
```
"serviceFabricCluster": {
    "clientCertificateId": "[resourceId('Microsoft.ApiManagement/service/certificates', parameters('ApimServiceName'), '[clientcertId]')]",
     ...
}
```
I have working code I can submit a PR for, but we'd need to update the API schema version. Lemme know your thoughts :)

**Comment by mirsaeedi** [comment]
Hey! Please send out the PR. I've already bump up the version. Please get the latest changes.

**Comment by levimatheri** [comment]
Okay, will submit a PR soon
