### ISSUE TITLE
Add Support for Named Value secrets using ARM SecureString parameter

### ISSUE THREAD

**Issue by andrewdmoreno** [mirsaeedi/dotnet-apim#5]
Not sure if there is a way to do this now but it would be great to be able to define named values as secrets that require their values to be passed in at deployment time via an arm `securestring` parameter. This would allow the value to be passed in securely and not visible anywhere.

**Comment by mirsaeedi** [comment]
I guess as a workaround, you can fetch the secret value in your CI/CD scripts and pass it to the tool using the [`-s` flag](https://github.com/mirsaeedi/dotnet-apim#passing-global-variables).

**Comment by mirsaeedi** [comment]
@andrewdmoreno Support for `NamedValue` is gonna be added by #16

**Comment by andrewdmoreno** [comment]
Just to have the full scenario documented here for historical purposes in the event I forget and need to refer to it in future:

The current solution added by #16 works great, however, when the named value is a secret, the secret value will be visible in plain text in the generated arm template. It would be nice if, in these cases, we could designate that the variable should be supplied by an arm parameter.

**Comment by mirsaeedi** [comment]
Hello Andrew. Sorry for the super later reply. There are two ways to achieve that:

1. You can always pass secrets via variables to the tool: `dotnet-apim -c "c:/apim/definition.yml" -s "apimInstanceName=value1;apimFolder=value2;uploadLocation=value3"`. In this case, you store secrets in key vault or ado pipeline variables, Then use a script to read them, and pass them to the tool.
2. You can manually define the NamedValue variables in APIM, and simply refer to them in the yml via `${namevalue}`
